
logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.leapwise.evalexp: DEBUG

spring:
  application:
    name: evalexp
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:evalexp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=LEGACY
    username: evalexp
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 5
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db/db.changelog-master.xml
server:
  port: 8080